
export const ENDPOINTS = [
    { label: "Paket E-Purchasing (Archive)", value: "/v1/ekatalog-archive/paket-e-purchasing" },
    { label: "Instansi / Satker (Archive)", value: "/v1/ekatalog-archive/instansi-satker" },
    { label: "Komoditas Detail (Archive)", value: "/v1/ekatalog-archive/komoditas-detail" },
    { label: "Penyedia Detail (Archive)", value: "/v1/ekatalog-archive/penyedia-detail" },
    { label: "Penyedia Distributor Detail (Archive)", value: "/v1/ekatalog-archive/penyedia-distributor-detail" },
    { label: "Paket E-Purchasing (Live)", value: "/v1/ekatalog/paket-e-purchasing" },
    { label: "Penyedia Detail (Live)", value: "/v1/ekatalog/penyedia-detail" },
    { label: "RUP Master Satker", value: "/v1/rup/master-satker" },
    { label: "RUP Paket Anggaran Penyedia", value: "/v1/rup/paket-anggaran-penyedia" },
    { label: "RUP Paket Anggaran Swakelola", value: "/v1/rup/paket-anggaran-swakelola" },
    { label: "RUP Paket Penyedia Terumumkan", value: "/v1/rup/paket-penyedia-terumumkan" },
    { label: "RUP Paket Penyedia Terumumkan (Legacy)", value: "/legacy/rup/paket-penyedia-terumumkan" },
    { label: "RUP Paket Swakelola Terumumkan", value: "/v1/rup/paket-swakelola-terumumkan" },
    { label: "RUP Program Master", value: "/v1/rup/program-master" },
    { label: "Tender: Jadwal Tahapan Non-Tender", value: "/v1/tender/jadwal-tahapan-non-tender" },
    { label: "Tender: Jadwal Tahapan Tender", value: "/v1/tender/jadwal-tahapan-tender" },
    { label: "Tender: Non-Tender Ekontrak Kontrak", value: "/v1/tender/non-tender-ekontrak-kontrak" },
    { label: "Tender: Non-Tender Pengumuman", value: "/v1/tender/non-tender-pengumuman" },
    { label: "Tender: Non-Tender Selesai", value: "/v1/tender/non-tender-selesai" },
    { label: "Tender: Pencatatan Non-Tender", value: "/v1/tender/pencatatan-non-tender" },
    { label: "Tender: Pencatatan Non-Tender Realisasi", value: "/v1/tender/pencatatan-non-tender-realisasi" },
    { label: "Tender: Pencatatan Swakelola", value: "/v1/tender/pencatatan-swakelola" },
    { label: "Tender: Pencatatan Swakelola Realisasi", value: "/v1/tender/pencatatan-swakelola-realisasi" },
    { label: "Tender: Pengumuman", value: "/v1/tender/pengumuman" },
    { label: "Tender: Peserta Tender", value: "/v1/tender/peserta-tender" },
    { label: "Tender: Tender Ekontrak Kontrak", value: "/v1/tender/tender-ekontrak-kontrak" },
    { label: "Tender: Tender Selesai Nilai", value: "/v1/tender/tender-selesai-nilai" },
];
